[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "python3 -m venv .venv",
  ".venv/bin/pip install --no-cache-dir -r backend/requirements.txt"
]

[phases.build]
cmds = []

[variables]
PIP_BREAK_SYSTEM_PACKAGES = "1"

[start]
cmd = ".venv/bin/python backend/run_prod.py"
